### ISSUE TITLE
No event type for m.fully_read

### ISSUE THREAD

**Issue by famedly-bot** [famedly/dart_matrix_api_lite#20]
In GitLab by @nico-famedly on Sep 23, 2021, 01:25

This makes us hardcode this type a few times in the SDK and various apps it seems, see https://gitlab.com/famedly/company/frontend/famedly-web/-/merge_requests/27 for example.

# DoR Bug report
- [ ] The issue title and description should be explained in English language.
- [ ] Description of current and expected behavior is understood.
- [ ] If necessary,  reproduction steps should be included.
- [ ] Every attached media (if applicable) includes a short description.
- [ ] Bug can be reproduced in the latest development version
- [ ] Severity is understood.
- [ ] Responsible squad has been identified (issue is labeled)
- [ ] There is a list of affected components if needed.
- [ ] There is an estimate on the effort to fix the bug.

**Comment by krille-chan** [comment]
Will be solved by https://github.com/famedly/product-management/issues/1902
